### ISSUE TITLE
License for the project

### ISSUE THREAD

**Issue by davidjrichardson** [UWCS/dcs-get-repackaged#2]
As of the moment, the project has no license. The current version of dcs-get uses an MIT license, and I personally prefer MIT to GNU GPL v3. Any thoughts on the matter?

**Comment by mcnutty26** [comment]
I think GPL is the better option because it mandates that derivative works must also disclose their source code. Surely the aim here is to ensure that dcs-get is and remains easily maintainable, something which is hard to do if features and updates could be implemented with closed source.

Ultimately this is unlikely to have much actual impact. Still, given the choice between the two, GPL seems like the more appropriate license.

**Comment by zed0** [comment]
I'd go for MIT, or at least something not as viral as the GPL.  While it's nice if people open source stuff they're working on too, I'd rather have someone use it and not open source their stuff than not use it at all.
How much freedom do you want to give people? https://blog.goeswhere.com/2009/04/the-free-software-definition/

**Comment by Veltas** [comment]
Bear in mind *I'm an advocate of free software*, go with MIT. We do not need to try and use copyleft to get contributions here, and likely people will screw up contributions regardless. What we're doing is unlikely to be reused anywhere, if it is in the future forks can go GPL if they wish. Keep it simple for now, use MIT.

**Comment by Veltas** [comment]
@mcnutty26 GPL is probably the 'better' option, but it doesn't make a difference to us and could only get in the way of development. I think we should stand aside and let it be MIT.

@zed0 I'd just like to interject for a moment. What do you mean 'viral'?

**Comment by zed0** [comment]
@Veltas https://en.wikipedia.org/wiki/Viral_license

**Comment by Veltas** [comment]
It says it's a derogatory term.

**Comment by davidjrichardson** [comment]
Given this discussion has died off, I'm assuming that it is alright to go with MIT? At a future point it is possible to go with GPL, but this cannot be said if GPL was to be chosen and it was wished that the project is moved to an MIT license.

**Comment by mcnutty26** [comment]
"Given this discussion has died off, **I'm assuming that it is alright to go with the licence I like the most**? At a future point it is possible to go with GPL, but this cannot be said if GPL was to be chosen and it was wished that the project is moved to an MIT license. **Therefore we should base our decision on which one is least likely to be a bad decision, instead of which one is better for the project**"

/s - just kidding really :D (and salty about GPL, as much as it's possible to get salty about a license)

**Comment by davidjrichardson** [comment]
MIT it is then :wink:
